---
  - hosts: app
    become: true
    become_user: root
    vars:
      fav:
        fruit: mango
    roles:
      - { role: apache, tags: www }
      - { role: php, tags: [ 'www', 'php' ] }
      - { role: frontend, tags: devopsdemo }
    tags: 
      - frontend
      
